spring.application.name=mini_project

#google authorization
spring.security.oauth2.client.registration.google.client-id=443324490900-4j8fn0i81l51vrmr7cbtt2rroe929egt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#github authorization
spring.security.oauth2.client.registration.github.client-id=Ov23lihMbLrW4RsjcYXU
spring.security.oauth2.client.registration.github.client-secret=2df67fa78e837f6c51d4fb8570c1c784f13c0eb3

#gmail link
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=devxpriyanshu@gmail.com
spring.mail.password=tkau cajt ltto zuvc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Jwt setup
jwt.secret=${JWT_SECRET}
jwt.expiration=60000

spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=raj
spring.datasource.password=raj123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===== OPTIONAL BUT USEFUL =====
spring.jpa.properties.hibernate.format_sql=true

